### ISSUE TITLE
Please update the php version of composer.json 

### ISSUE THREAD

**Issue by a970032** [Smile-SA/magento2-module-elasticsuite-shared-catalog#1]
Magento cloud version is 7.2.11 please change the composer.json can compatible with php version >=7

**Comment by adexandros** [comment]
It's been six months and still hasn't been updated

**Comment by mediact-pipelines** [comment]
Please make this happen!

**Comment by romainruaud** [comment]
Fixed.

Please use minor versions : 

- 1.0.1 for Magento 2.2.x 
- 1.1.0 for Magento 2.3.x
