### ISSUE TITLE
Magento 2.4.6 compatibility

### ISSUE THREAD

**Issue by Wohlie** [Smile-SA/magento2-module-elasticsuite-shared-catalog#12]
Hi, this module depends on `smile/elasticsuite:~2.10.0` and can't be installed on the newest version of `smile/elasticsuite:~2.11.0` for Magento 2.4.6 compatibility.

**Comment by mayrn-techdivision** [comment]
A timeline on this would be great as this is also blocking the 2.4.6 upgrade for us.

**Comment by rqsakai** [comment]
PR to fix this issue: https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog/pull/13

**Comment by romainruaud** [comment]
Tag 2.11.0 was published.

Thank you all
